title: "zhugejugher's Portfolio"
author: zhugejugher

only_build_toc_files: true
exclude_patterns:
  - .github/*
  - .pytest_cache/*
  - .venv/*

execute:
  execute_notebooks: "auto"

sphinx:
  config:
    myst_heading_anchors: 4
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]
